parameters:
    judge.class: Netrunnerdb\BuilderBundle\Services\Judge
    decks.class: Netrunnerdb\BuilderBundle\Services\Decks

services:
    judge:
        class: %judge.class%
        arguments: [@doctrine.orm.entity_manager]
    decks:
        class: %decks.class%
        arguments: [@doctrine.orm.entity_manager, @judge]

