Netrunnerdb\CardsBundle\Entity\Changelog:
  type: entity
  table: changelog
  fields:
    date:
      id: true
      type: string
      length: 10
      fixed: false
      nullable: false
    change:
      type: string
      length: 255
      fixed: false
      nullable: false
  lifecycleCallbacks: {  }
