Netrunnerdb\CardsBundle\Entity\Ruling:
    type: entity
    table: ruling
    manyToMany:
        cards:
            targetEntity: Card
            inversedBy: rulings
            joinTable:
                name: rulinglink
                joinColumns:
                    ruling_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    card_id:
                        referencedColumnName: id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        question:
            type: string
            length: '1024'
        answer:
            type: string
            length: '1024'
        creation:
            type: date
    lifecycleCallbacks: {  }
